# Generated by Django 2.2.7 on 2019-12-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20191212_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diesel_rate', models.FloatField(verbose_name='Diesel price')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleBusExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Bus')),
                ('expense_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.DayExpense')),
            ],
        ),
    ]
