# Generated by Django 2.2.7 on 2019-12-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_dayexpense_singlebusexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayexpense',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Bus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayexpense',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='SingleBusExpense',
        ),
    ]
