# Generated by Django 2.2.7 on 2019-12-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20191214_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayexpense',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='dayexpense',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='dayexpense',
            name='diesel_rate',
            field=models.FloatField(default=0, verbose_name='Diesel price'),
        ),
        migrations.CreateModel(
            name='SingleBusExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Bus')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.DayExpense')),
            ],
        ),
    ]
